### ISSUE TITLE
CJS support

### ISSUE THREAD

**Issue by danielwerg** [cijiugechu/vite-plugin-thumbhash#9]
Could you build for `cjs` as well as `esm`? Shouldn't be too hard to add support for because this plugin already using `tsup` to build package.

I'm getting following error in my project:
```
Failed to resolve "vite-plugin-thumbhash". This package is ESM only but it was tried to load by `require`.
```
I can't switch to `esm` because of my eslint setup.

**Comment by cijiugechu** [comment]
Updated in [this commit](https://github.com/cijiugechu/vite-plugin-thumbhash/commit/cc6c936a52a9d8800a1360bd4605ec2f2416902d), you can now use `cjs` by upgrading to `v0.1.6`.
